version: "3"

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /home/infra/monitoring-wandoor/vm-monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.0
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      # - /home/infra/monitoring-wandoor/vm-monitoring/grafana-data:/var/lib/grafana
      - ./loki-data:/loki
      - ./loki-wal:/wal
  tempo:
    image: grafana/tempo:2.4.1
    volumes:
      - /home/infra/monitoring-wandoor/vm-monitoring/tempo-config.yml:/etc/tempo/config.yml
    command: -config.file=/etc/tempo/config.yml
    restart: always
    ports:
      - "3200:3200" # HTTP API
      - "4320:4317" # OTLP gRPC
      - "4321:4318" # OTLP HTTP

  grafana:
    image: grafana/grafana:10.0.3
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - ./grafana-data:/var/lib/grafana
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    restart: always
