apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandoor-backend
  namespace: wandoor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wandoor-backend
  template:
    metadata:
      labels:
        app: wandoor-backend
    spec:
      initContainers:
        - name: download-otel-agent
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              wget -O /otel/opentelemetry-javaagent.jar \
              https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: backend
          image: jrtr1/wandoor-backend-app:backend-644f22bc433d1ab7b5759d00540d3f2fb2f04e4a
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@wandoor-db:1521/wandoor_db"
            - name: SERVER_PORT
              value: "8081"
            - name: REDIS_HOST
              value: "wandoor-db"
            - name: REDIS_PORT
              value: "6379"

            # Credential from Secret
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: REDIS_PASSWORD
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: MAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wandoor-backend-secrets
                  key: JWT_SECRET

            # OTEL - Traces, Metrics, Logs
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=wandoor-backend"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"
            - name: OTEL_LOGS_INCLUDE_STACKTRACE
              value: "true"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wandoor
spec:
  selector:
    app: wandoor-backend
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
