apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandoor-backend
  namespace: wandoor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wandoor-backend
  template:
    metadata:
      labels:
        app: wandoor-backend
    spec:
      # -- INIT CONTAINER (Download java agent)
      initContainers:
        - name: download-otel-agent
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              wget -O /otel/opentelemetry-javaagent.jar \
              https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: backend
          image: jrtr1/wandoor-backend-app:backend-f6138bd1b9737f780406919d9ecbb93a47ce31a8
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:oracle:thin:@wandoor-db:1521/wandoor_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "wandoor"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SERVER_PORT
              value: "8081"
            - name: REDIS_HOST
              value: "wandoor-db"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "rediswandoor"

            # ========================================
            # OTEL - TRACES, METRICS, LOGS
            # ========================================
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"

            # ENABLE TRACES, METRICS, LOGS
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"

            # Resource Attributes
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=wandoor-backend"
            - name: OTEL_TRACES_SAMPLER
              value: "always_on"

            # OPTIONAL â€” biar log structured lebih bagus
            - name: OTEL_LOGS_INCLUDE_STACKTRACE
              value: "true"

            # Java Agent Attachment
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"

          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      volumes:
        - name: otel-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wandoor
spec:
  selector:
    app: wandoor-backend
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30080
      protocol: TCP
