apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wandoor-backend-ingress
  namespace: wandoor
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: strip-api@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: api.wandoor.my.id
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8081
