apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-db
  namespace: wandoor
spec:
  serviceName: oracle-db
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: wandoor-db
      containers:
        - name: oracle-db
          image: gvenzl/oracle-free:23-slim
          ports:
            - containerPort: 1521
            - containerPort: 5500
          env:
            - name: ORACLE_PASSWORD
              value: "root"
            - name: ORACLE_DATABASE
              value: "wandoor_db"
            - name: APP_USER
              value: "wandoor"
            - name: APP_USER_PASSWORD
              value: "root"
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
          readinessProbe:
            exec:
              command:
                [
                  "/bin/sh",
                  "-c",
                  "echo 'SELECT 1 FROM dual;' | sqlplus -s system/root@XEPDB1",
                ]
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  namespace: wandoor
spec:
  type: ClusterIP
  selector:
    app: oracle-db
  ports:
    - name: oracle
      port: 1521
      targetPort: 1521
    - name: oracle-em
      port: 5500
      targetPort: 5500
