# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: wandoor-ingress
#   namespace: default
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web
# spec:
#   ingressClassName: traefik
#   rules:
#     - host: wandoor.my.id
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: backend-service
#                 port:
#                   number: 8081

#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend-service
#                 port:
#                   number: 80
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wandoor-frontend-ingress
  namespace: wandoor
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: app.wandoor.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
