apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: wandoor
type: Opaque
stringData:
  ORACLE_PASSWORD: "root"
  APP_USER_PASSWORD: "root"
adamalhafizh23_gmail_com@wandoor:/home/k8s-manifests$ ls
ingress.yaml          minikube-linux-amd64.1  oracle-db
minikube-linux-amd64  namespace.yaml          wandoor-backend
adamalhafizh23_gmail_com@wandoor:/home/k8s-manifests$ cat ingress.yaml 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wandoor-ingress
  namespace: wandoor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wandoor.local  # Ganti dengan domain Anda atau gunakan IP
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8081